---
title: "Srinivasa Ramanujan"
author: "Guilherme Hathy"
date: "10 de fevereiro de 2017"
output: pdf_document
---

```{r, include=FALSE}
#Carregando Bibiotecas
library(neuralnet)
library(SIT)
load.packages('quantmod')

```

```{r}
baixadados <- function(inicio, fim, tickers){
  data <- new.env()
getSymbols(tickers, src = 'yahoo', from = inicio, to = fim, env = data, set.symbolnames = T, auto.assign = T)
for(i in data$symbolnames) data[[i]] = adjustOHLC(data[[i]], use.Adjusted=T)
bt.prep(data, align='keep.all', fill.gaps = T)



prices <- as.numeric(data$prices)

return(prices)
}

```

```{r}
separadia <- function(dados,dias){


prices <- dados


diasgenerico = dias -1

t0<-as.numeric(prices)            
t0<-t0[-((length(t0)-diasgenerico):length(t0))]

i = 1
coluna = 2
while(i < dias){
  diasgenerico = diasgenerico - 1
  
  t2<-as.numeric(prices) [-seq(1,i,1)]  #Três dias antes
  t2<-t2[-((length(t2)-diasgenerico):length(t2))]
  
  t0 <- cbind(t0,t2)
  
  coluna = coluna + 1
  i = i + 1
}

colnames(t0) <- sprintf("x%d", 1:length(colnames(t0)))
return(t0)
}


```

```{r}

RMSE <- function(x, y){
  
  return( sqrt(mean((x-y)^2))    )
  
}
```

#Testando estrategias com dias diferentes e diferentes camadas.
```{r}
dados2016 <-  baixadados(inicio = '2016-01-01', fim = '2016-12-31', tickers = 'PETR4.SA')
dados2017 <-  baixadados(inicio = '2017-01-01', fim = '2017-12-31', tickers = 'PETR4.SA')

dias = 5
neuronio1 = 5
neuronio2 = 0
neuronio3 = 0
resultado <- data.frame(Dias = numeric(),Neuronio1 = numeric(),
                        Neuronio2 = numeric(), Neuronio3 = numeric(),
                        Resultado = numeric())

while(dias <= 15){
  while(neuronio1 <=25){
    while(neuronio2<=25){
      while(neuronio3 <= 25){
        
        dados2016dividido <- separadia(dados = dados2016, dias = dias)
        x <- as.formula(paste(sprintf("dados2016dividido[, %d] ~ ", dias),
                              paste(sprintf("dados2016dividido[, %d]", 
                                            1:(dias-1)), collapse = "+")))
        
        
        
        if(neuronio2 == 0  & neuronio3 > 0){
          
        }
        
        if(neuronio2 >0 & neuronio3 == 0){
          
          #Criando algoritmo
          algoritmo <- neuralnet(x,data=dados2016dividido, hidden=c(neuronio1,neuronio2))
          
          #Testando com dados de 2017
          dados2017dividido <- separadia(dados = dados2017,dias = dias)
          
          teste <- compute(algoritmo, dados2017dividido[,1:(dias - 1)])
          
          #Calculando RMSE
          resultadoRMSE <-  RMSE(x = teste$net.result, y = dados2017dividido[,dias])
    
    
          
          generico <- c(dias, neuronio1, neuronio2, 0, resultadoRMSE)
          resultado[nrow(resultado) + 1 ,] <- generico
        }
        if(neuronio2 == 0  & neuronio3 == 0){
           #Criando algoritmo
          algoritmo <- neuralnet(x,data=dados2016dividido, hidden=neuronio1)
          
          #Testando com dados de 2017
          dados2017dividido <- separadia(dados = dados2017,dias = dias)
          
          teste <- compute(algoritmo, dados2017dividido[,1:(dias - 1)])
          
          #Calculando RMSE
          resultadoRMSE <-  RMSE(x = teste$net.result, y = dados2017dividido[,dias])
          
          
          generico <- c(dias, neuronio1, 0, 0, resultadoRMSE)
          resultado[nrow(resultado) + 1 ,] <- generico
          
        }
        
        if(neuronio2 >0 & neuronio3 > 0){
          
           #Criando algoritmo
          algoritmo <- neuralnet(x,data=dados2016dividido, hidden=
                                   c(neuronio1,neuronio2,neuronio3))
          
          #Testando com dados de 2017
          dados2017dividido <- separadia(dados = dados2017,dias = dias)
          
          teste <- compute(algoritmo, dados2017dividido[,1:(dias - 1)])
          
          #Calculando RMSE
          resultadoRMSE <-  RMSE(x = teste$net.result, y = dados2017dividido[,dias])
          
          generico <- c(dias, neuronio1, neuronio2, neuronio3, resultadoRMSE)
          resultado[nrow(resultado) + 1 ,] <- generico
        }
        
        neuronio3 = neuronio3+5    
      }
      neuronio3 = 0
      neuronio2 = neuronio2+5
    }
    neuronio2 = 0
    neuronio1 = neuronio1 + 5
  }
  neuronio1 = 5
  dias = dias + 5
}



    
    
    
    
    
   
   
    
```

```{r}

# Melhores resultados
head(resultado[order(resultado$Resultado),])

```
